group: travis_lts
sudo: required

services:
- docker

env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - secure: "SEPoXlkoiW3V3kjtvsPlQr8gqMlsW+5NVg+FySHEO34Bljtx0WfOnaNO6wYjZ7J/S5KlGD5zYnyHNHCPazrcQ/d1s4fnJlSpl6ulBICOFP9GXw2kim06znt0TNMpMsAfB3dgH80sHgsEBuZhHZaj5qDNRQTK1cscjqlyq4fkiccPde2a1EF1+zAeqlHG9rQt/he1ttSlyfTDRjKWOmee+R+me41SbGs0IWLt5rhrfXxiBXCPTowPNOsh31BXhw2tYqfAIOYRXEm1OYiwplJEF1OPouqNHkH2Q5fXZ5kNrcwoW2SRSC1M+WqDqsH6STPxSd6EQEWSqyzlSB/a9CQ1jT1hd058DV/NzCEEOpbJy01tCya1+5QmaBFwsam24ayAwMdXXtLlP42ZA5STdLwZziO1FIG0f+pxsEyD97Np+5SojDTFzYFar4W8W0P81ItLxIO3uxuYgrRIU5/COKlJ1ecNOK6+AlyaUUwEABwOtFMiUNVjXebmuw9nW8Kn4IfsItZgDY39MtciV5/eqoMHbKV4dLCSFJ++d3PV/cBd3EmiRSkyjnxoQVYGe3ap7qyx/HjnmrjAhx96zzYw25c3iSDWwjUvvrzi9zwApl7nRjh6IfUkOLLEtYqokqHXDC6y5CesQYtNYMOhXowjjGxftxHVfFju1pIoxlaWMGR9gPQ="

script:
- docker build -t ${DOCKER_USERNAME}/apache-tomcat .
- >
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/apache-tomcat ${DOCKER_USERNAME}/apache-tomcat:latest
    docker tag ${DOCKER_USERNAME}/apache-tomcat ${DOCKER_USERNAME}/apache-tomcat:alpine
  else
    docker tag ${DOCKER_USERNAME}/apache-tomcat ${DOCKER_USERNAME}/apache-tomcat:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/apache-tomcat ${DOCKER_USERNAME}/apache-tomcat:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/apache-tomcat
